server:
  port: 8080
graphql:
  servlet:
    mapping: /graphql
    enabled: true
    corsEnabled: true
    exception-handlers-enabled: true
graphql.playground:
  mapping: /playground
  endpoint: /graphql
  enabled: true
  pageTitle: Playground
spring:
  datasource:
    url: jdbc:h2:mem:qlUser
    username: sa
    password: 
    driver-class-name: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yml
  kafka:
    producer:
      bootstrap-servers:
      - 127.0.0.1:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      group-id: group_id     
topic:
  name:
    prodducer: topico.comando.teste
    
auto:
  create:
    topics:
      enable: true