server:
 port: 8081
graphql:
  servlet:
    mapping: /graphql
    enabled: true
    corsEnabled: true
    exception-handlers-enabled: true
graphql.playground:
  mapping: /playground
  endpoint: /graphql
  enabled: true
  pageTitle: Playground
spring:
  datasource:
    url: jdbc:h2:mem:qlUser
    username: sa
    password: 
    driver-class-name: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  kafka:    consumer:      bootstrap-servers:      - 127.0.0.1:9092
      group-id: group_id
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

topic:
  name:
    consumer: topico.comando.teste
    
auto:
  create:
    topics:
      enable: true       